### ISSUE TITLE
DeepL Free APIを使う場合、api-free.deepl.comを使うオプションが必要

### ISSUE THREAD

**Issue by taku0815** [Y-RyuZU/MinecraftModsLocalizer#3]
twitterで見かけたため使ってみようと思い、最新版（1.4.0）にて実行したものの403 Forbidden Errorを吐いていたため調べたところ、deepL Free APIを使う場合はapi.deepl.comではなくapi-free.deepl.comにリクエストを送る必要があるそうです。
フォークをしてURLをそれに置き換えた物でテストしたところ、翻訳されるのを確認しました。

**Comment by Y-RyuZU** [comment]
ありがとうございます！チェックボックスを用意して対応しました！
