### ISSUE TITLE
Patchouliの翻訳機能

### ISSUE THREAD

**Issue by taku0815** [Y-RyuZU/MinecraftModsLocalizer#6]
ChatGPTの対応ありがとう！ありがたく使わせていただいております。

要望なのですがPatchouliというminecraft内でmodのドキュメントを本という形で読めるmodが存在しており、多くのmodがそのPatchouliの機能を使ってmodの説明をしているため、これもMinecraftModsLocalizerで翻訳出来たら便利だなと思いIssuesを上げさせてもらいました。

ご一考よろしくお願いいたします。

**Comment by Y-RyuZU** [comment]
リクエストありがとうございます。Patchouliの実装方法を確認できたので、近日中に対応できたらなと思います。

私用メモ
- /mod.jar/assetes/{mod_name}/patchouli_books/guidebook/en_us/ -> ja_jpのクローンをしてjsonを翻訳して埋め込む。

**Comment by Y-RyuZU** [comment]
対応しました。リクエストありがとうございました。
