### ISSUE TITLE
mac版とlinux版のモジュール依存関係について

### ISSUE THREAD

**Issue by taku0815** [Y-RyuZU/MinecraftModsLocalizer#8]
workflowのmac.yml linux.yml release.ymlのname:Install dependenciesにおいてpipでインストールしている依存関係のモジュールが足りてないようです。

pip install --no-cache-dir pyzipper requests pyinstaller PySimpleGUI ではなく
pip install --no-cache-dir pyzipper requests pyinstaller TkEasyGUI openai に変えたところ動作したことをforkした物で確認しました。

**Comment by Y-RyuZU** [comment]
ご報告ありがとうございます。
なぜかlinuxのみwindowsと異なりworkflowにてDockerを使用していなかったので、使用するように修正しました。
macosもDockerを使用するように変更しましたが、Dockerのインストールが長すぎて使えたものじゃなかったので直書きで依存関係だけを修正するように変更しました。
